import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import NextAuthProvider from '@/src/provider/authsession'
import { Toaster } from "@/components/ui/toaster"
import { cn } from '@/lib/utils'
import N_horizontal from '@/src/ui/navigation/n_horizontal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className={cn('light  text-slate-900 antialiased', inter.className)}>
			<body className="min-h-screen bg-slate-50  antialiased">
				<NextAuthProvider>
					<N_horizontal />
					<div className='container mx-auto h-full max-w-7xl pt-12'>
						{children}
					</div>
					<Toaster />
				</NextAuthProvider>
			</body>
		</html>
	)
}
